<a href="https://colab.research.google.com/github/20B01A0570/Weather_prediction/blob/main/Weather_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.Uploading  dataset into Google collab**

In [ ]:
'''https://www.codespeedy.com/weather-prediction-using-machine-learning-in-python/'''
from google.colab import files
uploaded = files.upload()

Saving temps2.csv to temps2.csv


**2.Importing Libraries**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

**3.Importing Data**

In [ ]:
data=pd.read_csv('temps2.csv', sep=';')
data.head(5)

Year  Month  Day  Hour  Minute  Temperature  Total Precipitation  \
0  2019      1    1     0       0         5.05                  0.0   
1  2019      1    1     1       0         4.90                  0.0   
2  2019      1    1     2       0         4.81                  0.0   
3  2019      1    1     3       0         4.73                  0.0   
4  2019      1    1     4       0         4.60                  0.0   

   Wind Speed  Wind Direction  
0        4.68          292.62  
1        4.69          302.47  
2        4.83          296.57  
3        5.35          289.65  
4        5.24          285.95

In [ ]:
data.describe()

Year        Month          Day         Hour  Minute  \
count  9192.000000  9192.000000  9192.000000  9192.000000  9192.0   
mean   2019.046997     6.266319    15.428198    11.500000     0.0   
std       0.211645     3.563437     8.760368     6.922563     0.0   
min    2019.000000     1.000000     1.000000     0.000000     0.0   
25%    2019.000000     3.000000     8.000000     5.750000     0.0   
50%    2019.000000     6.000000    15.000000    11.500000     0.0   
75%    2019.000000     9.000000    23.000000    17.250000     0.0   
max    2020.000000    12.000000    31.000000    23.000000     0.0   

       Temperature  Total Precipitation   Wind Speed  Wind Direction  
count  9192.000000          9192.000000  9192.000000     9192.000000  
mean     12.367080             0.072258    11.830767      200.764990  
std       7.858016             0.277092     8.805661       93.651518  
min      -3.750000             0.000000     0.000000        0.880000  
25%       6.040000             0.000000     5.690000      117.010000  
50%      11.630000             0.000000     9.290000      215.155000  
75%      17.980000             0.000000    15.380000      274.217500  
max      36.120000             5.700000    71.380000      360.000000

In [ ]:
data.shape

(9192, 9)

**4.Declaring Data**

In [ ]:
data = data[['Total Precipitation','Wind Speed','Wind Direction','Temperature']]
data.head()

Total Precipitation  Wind Speed  Wind Direction  Temperature
0                  0.0        4.68          292.62         5.05
1                  0.0        4.69          302.47         4.90
2                  0.0        4.83          296.57         4.81
3                  0.0        5.35          289.65         4.73
4                  0.0        5.24          285.95         4.60

**5.Cleaning Data (Checking for NULL values)**

In [ ]:
data.isnull()

Total Precipitation  Wind Speed  Wind Direction  Temperature
0                   False       False           False        False
1                   False       False           False        False
2                   False       False           False        False
3                   False       False           False        False
4                   False       False           False        False
...                   ...         ...             ...          ...
9187                False       False           False        False
9188                False       False           False        False
9189                False       False           False        False
9190                False       False           False        False
9191                False       False           False        False

[9192 rows x 4 columns]

**6.Creating Dependent Variables**

In [ ]:
x = data[['Total Precipitation','Wind Speed','Wind Direction']]
x = np.array(x)
x = x.reshape(len(x),3)

In [ ]:
x.shape

(9192, 3)

**7.Creating Independent variables**

In [ ]:
y = data[['Temperature']]
y = np.array(y)
y = y.reshape(len(y),1)

In [ ]:
y.shape

(9192, 1)

**8.Creating Data into Training and Testing Data**

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,test_size = 0.2,random_state=4)

In [ ]:
x_train

array([[  0.  ,  22.69, 268.18],
       [  0.  ,   6.41, 321.84],
       [  0.  ,   6.76, 295.2 ],
       ...,
       [  0.  ,  70.43, 260.59],
       [  0.  ,  23.22, 251.  ],
       [  0.  ,  11.72, 100.62]])

In [ ]:
x_test

array([[  0.  ,  10.8 , 126.87],
       [  0.  ,   5.41, 176.19],
       [  1.2 ,  37.88, 266.19],
       ...,
       [  0.  ,  19.81, 109.09],
       [  0.  ,  22.38, 117.8 ],
       [  0.  ,   6.44, 153.43]])

In [ ]:
y_train

array([[11.4 ],
       [ 3.17],
       [ 7.96],
       ...,
       [ 2.65],
       [14.03],
       [13.66]])

In [ ]:
y_test

array([[21.17],
       [19.99],
       [ 9.86],
       ...,
       [18.16],
       [ 8.59],
       [13.3 ]])

**9.Declaring Random Forest Algorithm**

In [ ]:
rf = RandomForestRegressor(n_estimators=1000,random_state=4)

**10.Training Data**

In [ ]:
rf.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(n_estimators=1000, random_state=4)

**11.Testing Data**

In [ ]:
pred = rf.predict(x_test)

In [ ]:
print(pred)

[14.18288738 16.2291701   8.39653    ... 14.0521925  13.94415381
  8.48850879]


**12.Calculating Accuracy**

In [ ]:
errors = abs(pred-y_test)

In [ ]:
print('Mean Absolute Error:',round(np.mean(errors),2),)

Mean Absolute Error: 7.38 degrees.
